/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/alwayscomb_packed_partSelect_svi.sv:15.1-23.10" *)
module top(o_a);
  (* src = "testcases/alwayscomb_packed_partSelect_svi.sv:16.24-16.27" *)
  output [7:0] o_a;
  wire [7:0] o_a;
  (* src = "testcases/alwayscomb_packed_partSelect_svi.sv:0.0-0.0" *)
  wire [7:0] \u_I.x ;
  assign o_a = 8'hxx;
  assign \u_I.x  = 8'hxx;
endmodule
