/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/assign_misc_port_Module2opt.sv:36.1-45.10" *)
module top(\u_I.w , \u_I.z , \u_I.x , \u_I.y );
  (* src = "testcases/assign_misc_port_Module2opt.sv:0.0-0.0" *)
  inout \u_I.w ;
  wire \u_I.w ;
  (* src = "testcases/assign_misc_port_Module2opt.sv:0.0-0.0" *)
  inout \u_I.x ;
  wire \u_I.x ;
  (* src = "testcases/assign_misc_port_Module2opt.sv:0.0-0.0" *)
  inout \u_I.y ;
  wire \u_I.y ;
  (* src = "testcases/assign_misc_port_Module2opt.sv:0.0-0.0" *)
  inout \u_I.z ;
  wire \u_I.z ;
endmodule
