/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/alwayscomb_misc_module_definition_port_only_svi.sv:27.1-34.10" *)
module top();
endmodule
