/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* is_interface =  1  *)
(* src = "testcases/alwayslatch_misc_port_scalarOutput.sv:0.0-0.0" *)
module I(i_en, o_a, i_a);
  (* src = "testcases/alwayslatch_misc_port_scalarOutput.sv:7.17-7.20" *)
  input i_a;
  wire i_a;
  (* src = "testcases/alwayslatch_misc_port_scalarOutput.sv:5.17-5.21" *)
  input i_en;
  wire i_en;
  (* src = "testcases/alwayslatch_misc_port_scalarOutput.sv:6.18-6.21" *)
  output o_a;
  wire o_a;
  assign o_a = 1'hx;
endmodule

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/alwayslatch_misc_port_scalarOutput.sv:75.1-87.10" *)
module top(i_en, o_a, i_a);
  (* src = "testcases/alwayslatch_misc_port_scalarOutput.sv:78.17-78.20" *)
  input i_a;
  wire i_a;
  (* src = "testcases/alwayslatch_misc_port_scalarOutput.sv:76.21-76.25" *)
  input i_en;
  wire i_en;
  (* src = "testcases/alwayslatch_misc_port_scalarOutput.sv:77.18-77.21" *)
  output o_a;
  wire o_a;
  (* is_interface = 32'd1 *)
  (* src = "testcases/alwayslatch_misc_port_scalarOutput.sv:81.5-81.13" *)
  I u_I (
    .i_a(i_a),
    .i_en(i_en),
    .o_a(o_a)
  );
endmodule
