/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/assign_misc_svi.sv:37.1-54.10" *)
module top(i_a, o_b);
  (* src = "testcases/assign_misc_svi.sv:38.17-38.20" *)
  input i_a;
  wire i_a;
  (* src = "testcases/assign_misc_svi.sv:39.18-39.21" *)
  output o_b;
  wire o_b;
  (* src = "testcases/assign_misc_svi.sv:52.29-52.37" *)
  wire \u_M1.o_b ;
  (* src = "testcases/assign_misc_svi.sv:52.18-52.26" *)
  wire \u_M2.o_b ;
  assign o_b = 1'h0;
  assign \u_M1.o_b  = 1'hx;
  assign \u_M2.o_b  = 1'hx;
endmodule
