/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/interface_input_interface.sv:22.1-39.10" *)
module top(i_a, i_b, o_a);
  (* src = "testcases/interface_input_interface.sv:23.17-23.20" *)
  input i_a;
  wire i_a;
  (* src = "testcases/interface_input_interface.sv:24.17-24.20" *)
  input i_b;
  wire i_b;
  (* src = "testcases/interface_input_interface.sv:25.18-25.21" *)
  output o_a;
  wire o_a;
  (* src = "testcases/interface_input_interface.sv:0.0-0.0" *)
  (* unused_bits = "0" *)
  wire \u_I1.x ;
  (* src = "testcases/interface_input_interface.sv:0.0-0.0" *)
  (* unused_bits = "0" *)
  wire \u_I1.y ;
  (* src = "testcases/interface_input_interface.sv:0.0-0.0" *)
  wire \u_I1.z ;
  assign o_a = 1'hx;
  assign \u_I1.x  = i_a;
  assign \u_I1.y  = i_b;
  assign \u_I1.z  = 1'hx;
endmodule
