/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/struct_svi_packed.sv:20.1-31.10" *)
module top(i_clk, o_a);
  (* src = "testcases/struct_svi_packed.sv:21.17-21.22" *)
  input i_clk;
  wire i_clk;
  (* src = "testcases/struct_svi_packed.sv:22.24-22.27" *)
  output [7:0] o_a;
  wire [7:0] o_a;
  (* src = "testcases/struct_svi_packed.sv:29.16-29.29" *)
  wire \u_I.data.data ;
  assign o_a = 8'b0000000x;
  assign \u_I.data.data  = 1'hx;
endmodule
