/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* is_interface =  1  *)
(* src = "testcases/alwayslatch_misc_port_vectorOutput.sv:0.0-0.0" *)
module I(i_en, o_a, i_a);
  (* src = "testcases/alwayslatch_misc_port_vectorOutput.sv:8.17-8.20" *)
  input i_a;
  wire i_a;
  (* src = "testcases/alwayslatch_misc_port_vectorOutput.sv:6.17-6.21" *)
  input i_en;
  wire i_en;
  (* src = "testcases/alwayslatch_misc_port_vectorOutput.sv:7.24-7.27" *)
  output [3:0] o_a;
  wire [3:0] o_a;
  assign o_a = 4'hx;
endmodule

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/alwayslatch_misc_port_vectorOutput.sv:76.1-88.10" *)
module top(i_en, o_a, i_a);
  (* src = "testcases/alwayslatch_misc_port_vectorOutput.sv:79.17-79.20" *)
  input i_a;
  wire i_a;
  (* src = "testcases/alwayslatch_misc_port_vectorOutput.sv:77.21-77.25" *)
  input i_en;
  wire i_en;
  (* src = "testcases/alwayslatch_misc_port_vectorOutput.sv:78.24-78.27" *)
  output [3:0] o_a;
  wire [3:0] o_a;
  (* is_interface = 32'd1 *)
  (* src = "testcases/alwayslatch_misc_port_vectorOutput.sv:82.5-82.13" *)
  I u_I (
    .i_a(i_a),
    .i_en(i_en),
    .o_a(o_a)
  );
endmodule
