/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/alwaysff_misc_differentInterfacesToOneInst.sv:88.1-110.10" *)
module top(i_clk, i_srst, i_arst);
  (* src = "testcases/alwaysff_misc_differentInterfacesToOneInst.sv:91.21-91.27" *)
  input i_arst;
  wire i_arst;
  (* src = "testcases/alwaysff_misc_differentInterfacesToOneInst.sv:89.21-89.26" *)
  input i_clk;
  wire i_clk;
  (* src = "testcases/alwaysff_misc_differentInterfacesToOneInst.sv:90.21-90.27" *)
  input i_srst;
  wire i_srst;
endmodule
