/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* is_interface =  1  *)
(* src = "testcases/alwayslatch_misc_svi_Modport.sv:0.0-0.0" *)
module I(i_clk, i_en, i_a, o_a);
  (* src = "testcases/alwayslatch_misc_svi_Modport.sv:8.23-8.26" *)
  input [3:0] i_a;
  wire [3:0] i_a;
  (* src = "testcases/alwayslatch_misc_svi_Modport.sv:6.17-6.22" *)
  input i_clk;
  wire i_clk;
  (* src = "testcases/alwayslatch_misc_svi_Modport.sv:7.17-7.21" *)
  input i_en;
  wire i_en;
  (* src = "testcases/alwayslatch_misc_svi_Modport.sv:9.24-9.27" *)
  output [3:0] o_a;
  wire [3:0] o_a;
  assign o_a = 4'hx;
endmodule

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/alwayslatch_misc_svi_Modport.sv:67.1-94.10" *)
module top(i_clk, i_en, o_a, i_a);
  (* src = "testcases/alwayslatch_misc_svi_Modport.sv:71.23-71.26" *)
  input [3:0] i_a;
  wire [3:0] i_a;
  (* src = "testcases/alwayslatch_misc_svi_Modport.sv:68.17-68.22" *)
  input i_clk;
  wire i_clk;
  (* src = "testcases/alwayslatch_misc_svi_Modport.sv:69.17-69.21" *)
  input i_en;
  wire i_en;
  (* src = "testcases/alwayslatch_misc_svi_Modport.sv:70.24-70.27" *)
  output [3:0] o_a;
  wire [3:0] o_a;
  (* is_interface = 32'd1 *)
  (* src = "testcases/alwayslatch_misc_svi_Modport.sv:74.5-76.6" *)
  I u_I (
    .i_a(i_a),
    .i_clk(i_clk),
    .i_en(i_en),
    .o_a(o_a)
  );
endmodule
