/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* is_interface =  1  *)
(* src = "testcases/alwayslatch_misc_svi_dotnameModuleInst.sv:0.0-0.0" *)
module I(i_clk, i_en, i_a, o_a);
  (* src = "testcases/alwayslatch_misc_svi_dotnameModuleInst.sv:7.17-7.20" *)
  input i_a;
  wire i_a;
  (* src = "testcases/alwayslatch_misc_svi_dotnameModuleInst.sv:5.17-5.22" *)
  input i_clk;
  wire i_clk;
  (* src = "testcases/alwayslatch_misc_svi_dotnameModuleInst.sv:6.17-6.21" *)
  input i_en;
  wire i_en;
  (* src = "testcases/alwayslatch_misc_svi_dotnameModuleInst.sv:8.18-8.21" *)
  output o_a;
  wire o_a;
  assign o_a = 1'hx;
endmodule

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/alwayslatch_misc_svi_dotnameModuleInst.sv:66.2-81.11" *)
module top(i_clk, i_en, o_a, i_a);
  (* src = "testcases/alwayslatch_misc_svi_dotnameModuleInst.sv:70.17-70.20" *)
  input i_a;
  wire i_a;
  (* src = "testcases/alwayslatch_misc_svi_dotnameModuleInst.sv:67.17-67.22" *)
  input i_clk;
  wire i_clk;
  (* src = "testcases/alwayslatch_misc_svi_dotnameModuleInst.sv:68.17-68.21" *)
  input i_en;
  wire i_en;
  (* src = "testcases/alwayslatch_misc_svi_dotnameModuleInst.sv:69.18-69.21" *)
  output o_a;
  wire o_a;
  (* is_interface = 32'd1 *)
  (* src = "testcases/alwayslatch_misc_svi_dotnameModuleInst.sv:73.5-75.6" *)
  I u_I (
    .i_a(i_a),
    .i_clk(i_clk),
    .i_en(i_en),
    .o_a(o_a)
  );
endmodule
