/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/assign_misc_inst.sv:69.1-89.10" *)
module top();
endmodule
