/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/struct_inst_packed.sv:14.1-26.10" *)
module top(i_clk, o_a);
  (* src = "testcases/struct_inst_packed.sv:15.17-15.22" *)
  input i_clk;
  wire i_clk;
  (* src = "testcases/struct_inst_packed.sv:16.24-16.27" *)
  output [7:0] o_a;
  wire [7:0] o_a;
  (* src = "testcases/struct_inst_packed.sv:22.5-22.18" *)
  wire \u_I.data.data ;
  assign o_a = 8'h01;
  assign \u_I.data.data  = 1'h1;
endmodule
