/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* top =  1  *)
(* dynports =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:26.1-45.10" *)
module top(i_clk, o_a, o_b, o_c);
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:27.17-27.22" *)
  input i_clk;
  wire i_clk;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:28.29-28.32" *)
  output [7:0] o_a;
  wire [7:0] o_a;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:29.29-29.32" *)
  output [7:0] o_b;
  wire [7:0] o_b;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:30.29-30.32" *)
  output [7:0] o_c;
  wire [7:0] o_c;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[0].x ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[0].y ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[0].z ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[1].x ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[1].y ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[1].z ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[2].x ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[2].y ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[2].z ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[3].x ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[3].y ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[3].z ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[4].x ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[4].y ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[4].z ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[5].x ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[5].y ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[5].z ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[6].x ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[6].y ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[6].z ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[7].x ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[7].y ;
  (* src = "testcases/alwaysff_arrayofSVI_svi_notimeunitInheritance.sv:0.0-0.0" *)
  wire \u_I[7].z ;
  assign o_a = 8'hxx;
  assign o_b = 8'hxx;
  assign o_c = 8'hxx;
  assign \u_I[0].x  = 1'hx;
  assign \u_I[0].y  = 1'hx;
  assign \u_I[0].z  = 1'hx;
  assign \u_I[1].x  = 1'hx;
  assign \u_I[1].y  = 1'hx;
  assign \u_I[1].z  = 1'hx;
  assign \u_I[2].x  = 1'hx;
  assign \u_I[2].y  = 1'hx;
  assign \u_I[2].z  = 1'hx;
  assign \u_I[3].x  = 1'hx;
  assign \u_I[3].y  = 1'hx;
  assign \u_I[3].z  = 1'hx;
  assign \u_I[4].x  = 1'hx;
  assign \u_I[4].y  = 1'hx;
  assign \u_I[4].z  = 1'hx;
  assign \u_I[5].x  = 1'hx;
  assign \u_I[5].y  = 1'hx;
  assign \u_I[5].z  = 1'hx;
  assign \u_I[6].x  = 1'hx;
  assign \u_I[6].y  = 1'hx;
  assign \u_I[6].z  = 1'hx;
  assign \u_I[7].x  = 1'hx;
  assign \u_I[7].y  = 1'hx;
  assign \u_I[7].z  = 1'hx;
endmodule
