/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/assign_packed_port.sv:27.1-41.10" *)
module top(i_a, o_a);
  (* src = "testcases/assign_packed_port.sv:28.17-28.20" *)
  input i_a;
  wire i_a;
  (* src = "testcases/assign_packed_port.sv:29.24-29.27" *)
  output [7:0] o_a;
  wire [7:0] o_a;
  (* src = "testcases/assign_packed_port.sv:0.0-0.0" *)
  wire [7:0] \u_I.x ;
  assign o_a = 8'hxx;
  assign \u_I.x  = 8'hxx;
endmodule
