/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/alwaysff_packed_inst.sv:10.1-25.10" *)
module top(i_a, i_clk, o_a);
  (* src = "testcases/alwaysff_packed_inst.sv:11.17-11.20" *)
  input i_a;
  wire i_a;
  (* src = "testcases/alwaysff_packed_inst.sv:12.17-12.22" *)
  input i_clk;
  wire i_clk;
  (* src = "testcases/alwaysff_packed_inst.sv:13.24-13.27" *)
  output [7:0] o_a;
  wire [7:0] o_a;
  (* src = "testcases/alwaysff_packed_inst.sv:0.0-0.0" *)
  wire [7:0] \u_I.x ;
  reg \u_I.x_reg[0] ;
  (* \always_ff  = 32'd1 *)
  (* src = "testcases/alwaysff_packed_inst.sv:18.3-21.6" *)
  always @(posedge i_clk)
    \u_I.x_reg[0]  <= i_a;
  assign \u_I.x [0] = \u_I.x_reg[0] ;
  assign o_a = { \u_I.x [0], \u_I.x [0], \u_I.x [0], \u_I.x [0], \u_I.x [0], \u_I.x [0], \u_I.x [0], \u_I.x [0] };
  assign \u_I.x [7:1] = { \u_I.x [0], \u_I.x [0], \u_I.x [0], \u_I.x [0], \u_I.x [0], \u_I.x [0], \u_I.x [0] };
endmodule
