/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/interface_modport_interface.sv:26.1-41.10" *)
module top(i_a, o_b);
  (* src = "testcases/interface_modport_interface.sv:27.17-27.20" *)
  input i_a;
  wire i_a;
  (* src = "testcases/interface_modport_interface.sv:28.18-28.21" *)
  output o_b;
  wire o_b;
  (* src = "testcases/interface_modport_interface.sv:0.0-0.0" *)
  (* unused_bits = "0" *)
  wire \u_I1.x ;
  (* src = "testcases/interface_modport_interface.sv:0.0-0.0" *)
  wire \u_I2.y ;
  assign o_b = 1'hx;
  assign \u_I1.x  = i_a;
  assign \u_I2.y  = 1'hx;
endmodule
