/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* is_interface =  1  *)
(* src = "testcases/alwayslatch_misc_svi_noModport.sv:0.0-0.0" *)
module I(i_clk, i_en, i_a, o_a);
  (* src = "testcases/alwayslatch_misc_svi_noModport.sv:7.23-7.26" *)
  input [3:0] i_a;
  wire [3:0] i_a;
  (* src = "testcases/alwayslatch_misc_svi_noModport.sv:5.17-5.22" *)
  input i_clk;
  wire i_clk;
  (* src = "testcases/alwayslatch_misc_svi_noModport.sv:6.17-6.21" *)
  input i_en;
  wire i_en;
  (* src = "testcases/alwayslatch_misc_svi_noModport.sv:8.24-8.27" *)
  output [3:0] o_a;
  wire [3:0] o_a;
  assign o_a = 4'hx;
endmodule

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/alwayslatch_misc_svi_noModport.sv:60.1-87.10" *)
module top(i_clk, i_en, o_a, i_a);
  (* src = "testcases/alwayslatch_misc_svi_noModport.sv:64.23-64.26" *)
  input [3:0] i_a;
  wire [3:0] i_a;
  (* src = "testcases/alwayslatch_misc_svi_noModport.sv:61.17-61.22" *)
  input i_clk;
  wire i_clk;
  (* src = "testcases/alwayslatch_misc_svi_noModport.sv:62.17-62.21" *)
  input i_en;
  wire i_en;
  (* src = "testcases/alwayslatch_misc_svi_noModport.sv:63.24-63.27" *)
  output [3:0] o_a;
  wire [3:0] o_a;
  (* is_interface = 32'd1 *)
  (* src = "testcases/alwayslatch_misc_svi_noModport.sv:67.5-69.6" *)
  I u_I (
    .i_a(i_a),
    .i_clk(i_clk),
    .i_en(i_en),
    .o_a(o_a)
  );
endmodule
