/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/alwayslatch_misc_inst.sv:13.1-22.10" *)
module \M1$interfaces$I (i_en, \u_I.y , \u_I.z );
  (* src = "testcases/alwayslatch_misc_inst.sv:15.17-15.21" *)
  input i_en;
  wire i_en;
  (* src = "testcases/alwayslatch_misc_inst.sv:20.16-20.21" *)
  wire \u_I.x ;
  (* src = "testcases/alwayslatch_misc_inst.sv:0.0-0.0" *)
  inout \u_I.y ;
  wire \u_I.y ;
  (* src = "testcases/alwayslatch_misc_inst.sv:0.0-0.0" *)
  inout \u_I.z ;
  wire \u_I.z ;
  assign \u_I.x  = 1'hx;
  assign \u_I.y  = 1'hx;
endmodule

(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/alwayslatch_misc_inst.sv:25.1-39.10" *)
module \M2$interfaces$I (i_en, \u_I.y , \u_I.z );
  (* src = "testcases/alwayslatch_misc_inst.sv:27.17-27.21" *)
  input i_en;
  wire i_en;
  (* src = "testcases/alwayslatch_misc_inst.sv:0.0-0.0" *)
  inout \u_I.y ;
  wire \u_I.y ;
  (* src = "testcases/alwayslatch_misc_inst.sv:0.0-0.0" *)
  inout \u_I.z ;
  reg \u_I.z ;
  (* src = "testcases/alwayslatch_misc_inst.sv:0.0-0.0" *)
  always @*
    if (i_en) \u_I.z  = \u_I.y ;
  (* src = "testcases/alwayslatch_misc_inst.sv:30.6-33.6" *)
  \M1$interfaces$I  u_M1 (
    .i_en(i_en),
    .\u_I.y (\u_I.y ),
    .\u_I.z (\u_I.z )
  );
endmodule

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/alwayslatch_misc_inst.sv:42.1-56.10" *)
module top(o_a, i_en);
  (* src = "testcases/alwayslatch_misc_inst.sv:44.17-44.21" *)
  input i_en;
  wire i_en;
  (* src = "testcases/alwayslatch_misc_inst.sv:43.18-43.21" *)
  output o_a;
  wire o_a;
  (* src = "testcases/alwayslatch_misc_inst.sv:0.0-0.0" *)
  (* unused_bits = "0" *)
  wire \u_I.y ;
  (* src = "testcases/alwayslatch_misc_inst.sv:0.0-0.0" *)
  wire \u_I.z ;
  (* src = "testcases/alwayslatch_misc_inst.sv:49.6-52.6" *)
  \M2$interfaces$I  u_M2 (
    .i_en(i_en),
    .\u_I.y (\u_I.y ),
    .\u_I.z (\u_I.z )
  );
  assign o_a = \u_I.z ;
endmodule
