/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/assign_packed_inst_generateLoopScheme.sv:10.1-22.10" *)
module top(i_a, o_a);
  (* src = "testcases/assign_packed_inst_generateLoopScheme.sv:11.17-11.20" *)
  input i_a;
  wire i_a;
  (* src = "testcases/assign_packed_inst_generateLoopScheme.sv:12.24-12.27" *)
  output [7:0] o_a;
  wire [7:0] o_a;
  (* src = "testcases/assign_packed_inst_generateLoopScheme.sv:0.0-0.0" *)
  wire [7:0] \u_I.x ;
  assign o_a = { i_a, i_a, i_a, i_a, i_a, i_a, i_a, i_a };
  assign \u_I.x  = { i_a, i_a, i_a, i_a, i_a, i_a, i_a, i_a };
endmodule
