/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/alwayscomb_packed_inst_bit_to_array.sv:12.1-22.10" *)
module top(i_a, o_a);
  (* src = "testcases/alwayscomb_packed_inst_bit_to_array.sv:13.17-13.20" *)
  input i_a;
  wire i_a;
  (* src = "testcases/alwayscomb_packed_inst_bit_to_array.sv:14.24-14.27" *)
  output [7:0] o_a;
  wire [7:0] o_a;
  (* src = "testcases/alwayscomb_packed_inst_bit_to_array.sv:0.0-0.0" *)
  wire [7:0] \u_I.x ;
  assign o_a = { 7'h00, i_a };
  assign \u_I.x  = { 7'h00, i_a };
endmodule
