/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* is_interface =  1  *)
(* src = "testcases/assign_arrayofSVI_svi.sv:0.0-0.0" *)
module I(i_a, o_a, o_b);
  (* src = "testcases/assign_arrayofSVI_svi.sv:19.9-19.10" *)
  wire Z;
  (* src = "testcases/assign_arrayofSVI_svi.sv:11.17-11.20" *)
  input i_a;
  wire i_a;
  (* src = "testcases/assign_arrayofSVI_svi.sv:12.18-12.21" *)
  output o_a;
  wire o_a;
  (* src = "testcases/assign_arrayofSVI_svi.sv:13.18-13.21" *)
  output o_b;
  wire o_b;
  (* src = "testcases/assign_arrayofSVI_svi.sv:16.9-16.10" *)
  wire x;
  (* src = "testcases/assign_arrayofSVI_svi.sv:17.9-17.10" *)
  wire y;
  assign Z = 1'h0;
  assign o_a = 1'h0;
  assign o_b = i_a;
  assign x = i_a;
  assign y = 1'h0;
endmodule

(* top =  1  *)
(* dynports =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/assign_arrayofSVI_svi.sv:29.1-41.10" *)
module top(i_a, o_a, o_b);
  (* src = "testcases/assign_arrayofSVI_svi.sv:30.17-30.20" *)
  input i_a;
  wire i_a;
  (* src = "testcases/assign_arrayofSVI_svi.sv:31.29-31.32" *)
  output [7:0] o_a;
  wire [7:0] o_a;
  (* src = "testcases/assign_arrayofSVI_svi.sv:32.29-32.32" *)
  output [7:0] o_b;
  wire [7:0] o_b;
  (* is_interface = 32'd1 *)
  (* src = "testcases/assign_arrayofSVI_svi.sv:35.5-39.6" *)
  I \u_I[0]  (
    .i_a(i_a),
    .o_a(o_a[0]),
    .o_b(o_b[0])
  );
  (* is_interface = 32'd1 *)
  (* src = "testcases/assign_arrayofSVI_svi.sv:35.5-39.6" *)
  I \u_I[1]  (
    .i_a(i_a),
    .o_a(o_a[1]),
    .o_b(o_b[1])
  );
  (* is_interface = 32'd1 *)
  (* src = "testcases/assign_arrayofSVI_svi.sv:35.5-39.6" *)
  I \u_I[2]  (
    .i_a(i_a),
    .o_a(o_a[2]),
    .o_b(o_b[2])
  );
  (* is_interface = 32'd1 *)
  (* src = "testcases/assign_arrayofSVI_svi.sv:35.5-39.6" *)
  I \u_I[3]  (
    .i_a(i_a),
    .o_a(o_a[3]),
    .o_b(o_b[3])
  );
  (* is_interface = 32'd1 *)
  (* src = "testcases/assign_arrayofSVI_svi.sv:35.5-39.6" *)
  I \u_I[4]  (
    .i_a(i_a),
    .o_a(o_a[4]),
    .o_b(o_b[4])
  );
  (* is_interface = 32'd1 *)
  (* src = "testcases/assign_arrayofSVI_svi.sv:35.5-39.6" *)
  I \u_I[5]  (
    .i_a(i_a),
    .o_a(o_a[5]),
    .o_b(o_b[5])
  );
  (* is_interface = 32'd1 *)
  (* src = "testcases/assign_arrayofSVI_svi.sv:35.5-39.6" *)
  I \u_I[6]  (
    .i_a(i_a),
    .o_a(o_a[6]),
    .o_b(o_b[6])
  );
  (* is_interface = 32'd1 *)
  (* src = "testcases/assign_arrayofSVI_svi.sv:35.5-39.6" *)
  I \u_I[7]  (
    .i_a(i_a),
    .o_a(o_a[7]),
    .o_b(o_b[7])
  );
endmodule
