/* Generated by Yosys 0.27 (git sha1 5f88c218b, gcc 8.5.0 -fPIC -Os) */

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "testcases/alwayscomb_misc_modport_selection_module_definition.sv:57.1-70.10" *)
module top();
endmodule
